import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Igbob
 */
public class Films extends javax.swing.JFrame {

    /**
     * Creates new form Films
     */
    public Films() {
        initComponents();
        DatabaseConnection db = new DatabaseConnection();
        ResultSet rs = db.displayFilm();
        tableFilm.setModel(DbUtils.resultSetToTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filmLabel = new javax.swing.JLabel();
        addDataB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFilm = new javax.swing.JTable();
        filmMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filmLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        filmLabel.setText("Films");

        addDataB.setText("ADD DATA");
        addDataB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataBActionPerformed(evt);
            }
        });

        tableFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "film_id", "Title", "Description", "Release_year", "Language_id", "OG_language_id", "rental_duration", "rental_rate", "length", "replacement_cost", "rating", "special_features", "last_update"
            }
        ));
        jScrollPane1.setViewportView(tableFilm);

        filmMainMenu.setText("MAIN MENU");
        filmMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(filmLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(addDataB)
                        .addGap(163, 163, 163)
                        .addComponent(filmMainMenu)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDataB)
                    .addComponent(filmMainMenu))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDataBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataBActionPerformed
        String title = JOptionPane.showInputDialog(this,"Input the title of the movie.");
        String des = JOptionPane.showInputDialog(this,"Input the description of the movie.");
        int year = Integer.parseInt(JOptionPane.showInputDialog(this,"Input the year of the movie."));
        int languageId = Integer.parseInt(JOptionPane.showInputDialog(this,"Input the language ID of the movie."));
        int ogLanguage = Integer.parseInt(JOptionPane.showInputDialog(this,"Input the original language ID."));
        int rental = Integer.parseInt(JOptionPane.showInputDialog(this,"Input the rental duration"));
        double rental_rate = Double.parseDouble(JOptionPane.showInputDialog(this,"Input the rental rate of the movie."));
        int length = Integer.parseInt(JOptionPane.showInputDialog(this,"Input the length of the movie."));
        double replace = Double.parseDouble(JOptionPane.showInputDialog(this,"Input the replacement cost of the movie."));
        String rating = JOptionPane.showInputDialog(this,"Input the rating of the movie.");
        String special = JOptionPane.showInputDialog(this,"Input the special features of the movie.");
        
        DatabaseConnection db = new DatabaseConnection();
        db.insertFilm(title, des, year, languageId, ogLanguage, rental, rental_rate, length, replace, rating, special);
        ResultSet rs = db.displayFilm();
        tableFilm.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_addDataBActionPerformed

    private void filmMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmMainMenuActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_filmMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Films().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDataB;
    private javax.swing.JLabel filmLabel;
    private javax.swing.JButton filmMainMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFilm;
    // End of variables declaration//GEN-END:variables
}
